version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "America/Los_Angeles"
    commit-message:
      prefix: "[dependabot]"
    groups:
      website-all:
        patterns:
          - "*"
        update-types:
          - "major"
          - "minor"
          - "patch"
    open-pull-requests-limit: 1
