{% set data = load_setup_py_data(setup_file="../setup.py", from_recipe_dir=True) %}

package:
  name: {{ data.get("name")|lower }}
  version: {{ data.get("version") }}

source:
  path: ..

build:
  noarch: python
  script: "$PYTHON setup.py install --single-version-externally-managed --record=record.txt"

requirements:
  host:
    - python>=3.9
    - setuptools
  run:
    - numpy<2.0
    - pytorch>=1.10
    - matplotlib-base
    - tqdm
    - packaging

test:
  imports:
    - captum

about:
  home: https://captum.ai
  license: BSD-3
  license_file: LICENSE
  summary: Model interpretability for PyTorch
  description: |
    Captum is a model interpretability and understanding library for PyTorch.
    Captum means comprehension in Latin and contains general purpose implementations
    of integrated gradients, saliency maps, smoothgrad, vargrad and others for
    PyTorch models. It has quick integration for models built with domain-specific
    libraries such as torchvision, torchtext, and others.
  doc_url: https://captum.ai
  dev_url: https://github.com/pytorch/captum
