name: Captum Lint

on:
  pull_request:
  push:
    branches:
      - nightly
      - main
      - release/*

  workflow_dispatch:

env:
  CHANNEL: "nightly"

jobs:
  tests:
    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
    with:
      runner: linux.12xlarge
      docker-image: cimg/python:3.6
      repository: pytorch/captum
      script: |
        sudo chmod -R 777 .
        ./scripts/install_via_pip.sh
        ufmt check .
        flake8
        sphinx-build -WT --keep-going sphinx/source sphinx/build
