name: Captum Lint

on:
  pull_request:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  tests:
    # Make sure your runner has these labels (or just "self-hosted")
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Lint & docs
        run: |
          sudo chmod -R 777 .
          ./scripts/install_via_pip.sh
          ufmt check .
          flake8
          sphinx-build -WT --keep-going sphinx/source sphinx/build
