name: Unit-tests for Pip install

on:
  pull_request:
  push:
    branches:
      - nightly
      - main
      - release/*

  workflow_dispatch:

env:
  CHANNEL: "nightly"

jobs:
  tests:
    strategy:
      matrix:
        python_version: ["3.6"]
        pytorch_args: ["", "-n", "-v 1.6", "-v 1.7", " -v 1.8", "-v 1.9"]
      fail-fast: false
    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
    with:
      runner: linux.12xlarge
      repository: pytorch/captum
      script: |

        # Create Conda Env
        #conda create -yp ci_env python="${PYTHON_VERSION}"
        #conda activate /pytorch/captum/ci_env
        ./scripts/install_via_pip.sh ${{ matrix.pytorch_args }}

        # Run Tests
        python3 -m pytest -ra --cov=. --cov-report term-missing
